repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/prettier/prettier
    rev: 1.17.0
    hooks:
      - id: prettier
